In [1]:
import pandas as pd
import numpy as np

In [2]:
!ls
maindata = pd.read_excel('Zipcode data 070102023.xlsx')# load

 adi_with_avgstateranks.csv		  sdoh_modeling.ipynb
'CA_2020_ADI_9 Digit Zip Code_v3.2.csv'   socialDetJoin.ipynb
 cal_sdoh_useful.csv			  zipcode_coded.csv
 modeling.ipynb				 'Zipcode data 070102023.xlsx'
 SDOH_2020_ZIPCODE_1_0.xlsx		  zipcode_with_sdoh_only.csv

In [3]:
maindata.columns

Index(['Fiscal Year', 'ECG', 'Mutated MRN', 'Delivery method', 'Term/Preterm',
       'Induction', 'Singleton/Multiple', 'Multips', 'Racial/Ethnicity',
       'HDP Diagnosis (Y/N)', 'HDP Diagnosis (delivery episode)',
       'Diabetes (Y/N)', 'Type of DM', 'Meth/Cocaine use(Y/N)',
       'Readmitted (Y/N)', 'HDP Diagnosis (readmission episode) or NA',
       'Delivery Date', 'Readmission date', 'Age', 'BMI prepregnancy',
       'BMI close to delivery', 'zipcode_5digitis_mutated',
       'Zipcode_last4_mutated', 'On HDP meds at dc from birth episode (Y/N)',
       'If Y, how many?', 'Betablocker dose at dc', 'Nifedipine dose at dc',
       'Other meds at dc', 'Notes'],
      dtype='object')

In [4]:
maindata['ZIPCODE'] =(maindata['zipcode_5digitis_mutated']-12345).astype('Int64')
maindata['Zipcode_last4'] =(maindata['Zipcode_last4_mutated']-1234).astype('Int64')
maindata=maindata.drop(columns=['zipcode_5digitis_mutated', 'Zipcode_last4_mutated'])

In [5]:
maindata['Zipcode_last4']

0      2231
1      9739
2      <NA>
3      <NA>
4      <NA>
       ...
730    <NA>
731    2945
732    <NA>
733    <NA>
734    <NA>
Name: Zipcode_last4, Length: 735, dtype: Int64

In [6]:
maindata['ZIP_4'] = maindata['ZIPCODE']*10000 + maindata['Zipcode_last4']

In [7]:
maindata['ZIP_4']

0      958232231
1      957269739
2           <NA>
3           <NA>
4           <NA>
         ...
730         <NA>
731    956912945
732         <NA>
733         <NA>
734         <NA>
Name: ZIP_4, Length: 735, dtype: Int64

In [8]:
maindata.head()

,Fiscal Year,ECG,Mutated MRN,Delivery method,Term/Preterm,Induction,Singleton/Multiple,Multips,Racial/Ethnicity,HDP Diagnosis (Y/N),...,BMI close to delivery,On HDP meds at dc from birth episode (Y/N),"If Y, how many?",Betablocker dose at dc,Nifedipine dose at dc,Other meds at dc,Notes,ZIPCODE,Zipcode_last4,ZIP_4
0,2021,"Y, 4 month prior to del",7887439,"Vaginal, Spontaneous",Term,Y,Singleton,Y,Middle Eastern,Y,...,35.1,N,NaN,NaN,NaN,NaN,"Refugee, care started at 16 weeks, unilateral ...",95823,2231,958232231
1,2021,"Y, in labor",2392172,"Vaginal, Spontaneous",Term,Y,Singleton,Y,White,Y,...,32.9,Y,1.0,NaN,30 BID,NaN,NaN,95726,9739,957269739
2,2021,"Y, postpartum",1252118,"Vaginal, Spontaneous",Term,Y,Singleton,Y,White,N,...,26,N,NaN,NaN,NaN,NaN,postpartum headache,95678,<NA>,<NA>
3,2021,N,7872701,"Vaginal, Spontaneous",Term,Y,Singleton,Y,Middle Eastern,Y,...,31.4,Y,2.0,400 TID,30 daily,NaN,"postpartum readmission twice, finally controll...",95822,<NA>,<NA>
4,2021,N,7954972,Scheduled C-section,Term,N,Singleton,Y,Hispanic,Y,...,29.2,N,NaN,NaN,NaN,NaN,"IVF, immigrated at 30 weeks",95833,<NA>,<NA>

In [9]:
maindata.describe()

,Fiscal Year,Mutated MRN,Delivery Date,Age,"If Y, how many?",ZIPCODE,Zipcode_last4,ZIP_4
count,735.000000,7.350000e+02,735,273.000000,83.000000,272.0,120.0,120.0
mean,2022.795918,6.749585e+06,2023-01-09 12:42:07.346938624,32.783883,1.204819,95444.606618,4540.65,951237540.65
min,2019.000000,8.595970e+05,2019-07-19 00:00:00,15.000000,1.000000,30004.0,56.0,300040693.0
25%,2023.000000,7.295639e+06,2023-01-30 00:00:00,29.000000,1.000000,95629.5,2330.75,956274257.75
50%,2023.000000,7.851043e+06,2023-03-08 00:00:00,33.000000,1.000000,95757.0,4082.5,957476806.5
75%,2023.000000,8.111952e+06,2023-04-18 12:00:00,37.000000,1.000000,95827.25,6627.5,958262494.0
max,2023.000000,8.584249e+06,2023-05-31 00:00:00,54.000000,5.000000,96161.0,9739.0,961581719.0
std,0.711321,2.456225e+06,NaN,6.200762,0.557849,4007.311799,2618.608819,60247624.282125

In [10]:
maindata=maindata.drop(maindata[maindata['Readmitted (Y/N)'].isna()].index)
maindata=maindata.reset_index(drop=True)

In [11]:
print(maindata['Delivery method'].unique())
maindata.loc[maindata['Delivery method'].str.lower().str.contains('vaginal'),'Delivery method']='vaginal'
maindata.loc[maindata['Delivery method'].str.lower().str.contains('vbac'),'Delivery method']='vaginal'


maindata.loc[maindata['Delivery method'].str.lower().str.contains('c-section'),'Delivery method']='c-section'
maindata.loc[maindata['Delivery method'].str.lower().str.contains('cesarean hysterectomy'),'Delivery method']='c-section'

['Vaginal, Spontaneous' 'Scheduled C-section' 'Unscheduled C-section, AOD'
 'Scheduled C-Section, PTL' 'Unscheduled C-section, FIOL'
 'Unscheduled C-section, Breech' 'Unscheduled C-section, NRFHT'
 'Vacuum-assisted vaginal delivery' 'Scheduled C-section, Twins/PreE'
 'Scheduled C-section, failed ECV' 'Cesarean hysterectomy'
 'Scheduled C-section, twins' 'VBAC' 'Unscheduled C-Section, TOLAC'
 'Scheduled C-Section' 'Unscheduled C-Section, FIOL'
 'Scheduled C-Section, Breech' 'Unscheduled C-Section, AOD'
 'C-Section, Low Transverse' 'Vaginal, Breech' 'C-Section'
 'Unscheduled C-Section, abruption' 'scheduled C-Section'
 'scheduled, C-section' 'C-Section, Hysterectomy'
 'Forceps-assisted vaginal delivery' 'Scheduled c-section'
 'C-Section, T incision' 'C-Section, classical' 'C-Section, T-incision'
 'C-Section, hysterectomy']

In [12]:
maindata['Delivery method'].unique()

array(['vaginal', 'c-section'], dtype=object)

In [13]:
"""
'Delivery method' ,Racial/Ethnicity,'Type of DM','Term/Preterm', 'Induction',
'Singleton/Multiple',â€™Multipsâ€™,'HDP Diagnosis (Y/N)',
'HDP Diagnosis (delivery episode)'
"""

"\n'Delivery method' ,Racial/Ethnicity,'Type of DM','Term/Preterm', 'Induction',\n'Singleton/Multiple',â€™Multipsâ€™,'HDP Diagnosis (Y/N)',\n'HDP Diagnosis (delivery episode)'\n"

In [14]:
maindata['Racial/Ethnicity'].unique()

array(['Middle Eastern', 'White', 'Hispanic', 'AA', 'Asian',
       'Mixed (Asian, White)', 'Other', 'Mixed (Asian, White, AA)',
       'Declined', nan, 'Pacific islander', 'Unknown', 'A',
       'American Indian', 'Native Hawaiian'], dtype=object)

In [15]:
maindata['Racial/Ethnicity'].value_counts()

Racial/Ethnicity
White                       141
Asian                        58
Hispanic                     50
AA                           38
Other                        25
Declined                     17
Middle Eastern                6
Unknown                       3
American Indian               2
Mixed (Asian, White)          1
Mixed (Asian, White, AA)      1
Pacific islander              1
A                             1
Native Hawaiian               1
Name: count, dtype: int64

In [16]:
maindata[maindata['Racial/Ethnicity']=='Unknown']['Readmitted (Y/N)']

96     N
345    N
347    N
Name: Readmitted (Y/N), dtype: object

In [17]:
"""'Pacific islander', 'Unknown', 'A',
       'American Indian', 'Native Hawaiian'"""
maindata = maindata.drop(maindata[maindata['Racial/Ethnicity']=='Pacific islander'].index)
maindata = maindata.drop(maindata[maindata['Racial/Ethnicity']=='Unknown'].index)
maindata = maindata.drop(maindata[maindata['Racial/Ethnicity']=='A'].index)
maindata = maindata.drop(maindata[maindata['Racial/Ethnicity']=='American Indian'].index)
maindata = maindata.drop(maindata[maindata['Racial/Ethnicity']=='Native Hawaiian'].index)

In [18]:
maindata['Racial/Ethnicity'].unique()

array(['Middle Eastern', 'White', 'Hispanic', 'AA', 'Asian',
       'Mixed (Asian, White)', 'Other', 'Mixed (Asian, White, AA)',
       'Declined', nan], dtype=object)

In [19]:
maindata['Type of DM'].unique()

array(['A2GDM', nan, 'T1', 'A1GDM', 'T2DM', 'T1DM', 'N'], dtype=object)

In [20]:
maindata[maindata['Term/Preterm']=='Term/Preterm']

Empty DataFrame
Columns: [Fiscal Year, ECG, Mutated MRN, Delivery method, Term/Preterm, Induction, Singleton/Multiple, Multips, Racial/Ethnicity, HDP Diagnosis (Y/N), HDP Diagnosis (delivery episode), Diabetes (Y/N), Type of DM, Meth/Cocaine use(Y/N), Readmitted (Y/N), HDP Diagnosis (readmission episode) or NA, Delivery Date, Readmission date, Age, BMI prepregnancy, BMI close to delivery, On HDP meds at dc from birth episode (Y/N), If Y, how many?, Betablocker dose at dc, Nifedipine dose at dc, Other meds at dc, Notes, ZIPCODE, Zipcode_last4, ZIP_4]
Index: []

[0 rows x 30 columns]

In [21]:
print(maindata['Term/Preterm'].unique())
print(maindata['Induction'].unique())
print(maindata['Singleton/Multiple'].unique())
print(maindata['Multips'].unique())
print(maindata['HDP Diagnosis (Y/N)'].unique())
print(maindata['HDP Diagnosis (delivery episode)'].unique())

['Term' 'Preterm']
['Y' 'N' nan]
['Singleton' 'Multiple']
['Y' 'N' nan]
['Y' 'N']
['gestational hypertension' 'preeclampsia with SF' nan
 'superimposed with SF' 'chronic hypertension' 'preeclampsia without SF'
 'superimposed without SF' 'superimposed with SF w/ SF' 'none'
 'gestaional hypertension' 'prreclampsia without SF' 'preclampsia with SF'
 'chornic hypertension']

In [22]:
print(maindata['Induction'].isna().sum(),maindata['Induction'].isna().sum()*100/len(maindata['Induction']))

30 8.695652173913043

In [23]:
print(maindata[maindata['HDP Diagnosis (delivery episode)'].isna()]['Readmitted (Y/N)'])

2      Y
7      Y
14     Y
16     Y
21     Y
      ..
212    N
222    N
228    N
230    N
342    Y
Name: Readmitted (Y/N), Length: 90, dtype: object

In [24]:
maindata.loc[maindata['HDP Diagnosis (delivery episode)']=='gestaional hypertension','HDP Diagnosis (delivery episode)']='gestational hypertension'
maindata.loc[maindata['HDP Diagnosis (delivery episode)']=='prreclampsia without SF','HDP Diagnosis (delivery episode)']='preeclampsia without SF'
maindata.loc[maindata['HDP Diagnosis (delivery episode)']=='preclampsia with SF','HDP Diagnosis (delivery episode)']='preeclampsia with SF'
maindata.loc[maindata['HDP Diagnosis (delivery episode)']=='chornic hypertension','HDP Diagnosis (delivery episode)']='chronic hypertension'
maindata.loc[maindata['HDP Diagnosis (delivery episode)'].isna(),'HDP Diagnosis (delivery episode)']='No Episode'

In [25]:
print(maindata['HDP Diagnosis (delivery episode)'].unique())

['gestational hypertension' 'preeclampsia with SF' 'No Episode'
 'superimposed with SF' 'chronic hypertension' 'preeclampsia without SF'
 'superimposed without SF' 'superimposed with SF w/ SF' 'none']

In [26]:
"""
'Delivery method' ,Racial/Ethnicity,'Type of DM','Term/Preterm', 'Induction',
'Singleton/Multiple',â€™Multipsâ€™,'HDP Diagnosis (Y/N)',
'HDP Diagnosis (delivery episode)'
"""

"\n'Delivery method' ,Racial/Ethnicity,'Type of DM','Term/Preterm', 'Induction',\n'Singleton/Multiple',â€™Multipsâ€™,'HDP Diagnosis (Y/N)',\n'HDP Diagnosis (delivery episode)'\n"

In [27]:
temp_one_hot = pd.get_dummies(maindata['Delivery method'])
maindata = maindata.drop('Delivery method',axis = 1)
# Join the encoded df
maindata = maindata.join(temp_one_hot,rsuffix='_DeliveryMethod')
maindata

,Fiscal Year,ECG,Mutated MRN,Term/Preterm,Induction,Singleton/Multiple,Multips,Racial/Ethnicity,HDP Diagnosis (Y/N),HDP Diagnosis (delivery episode),...,"If Y, how many?",Betablocker dose at dc,Nifedipine dose at dc,Other meds at dc,Notes,ZIPCODE,Zipcode_last4,ZIP_4,c-section,vaginal
0,2021,"Y, 4 month prior to del",7887439,Term,Y,Singleton,Y,Middle Eastern,Y,gestational hypertension,...,NaN,NaN,NaN,NaN,"Refugee, care started at 16 weeks, unilateral ...",95823,2231,958232231,False,True
1,2021,"Y, in labor",2392172,Term,Y,Singleton,Y,White,Y,preeclampsia with SF,...,1.0,NaN,30 BID,NaN,NaN,95726,9739,957269739,False,True
2,2021,"Y, postpartum",1252118,Term,Y,Singleton,Y,White,N,No Episode,...,NaN,NaN,NaN,NaN,postpartum headache,95678,<NA>,<NA>,False,True
3,2021,N,7872701,Term,Y,Singleton,Y,Middle Eastern,Y,superimposed with SF,...,2.0,400 TID,30 daily,NaN,"postpartum readmission twice, finally controll...",95822,<NA>,<NA>,False,True
4,2021,N,7954972,Term,N,Singleton,Y,Hispanic,Y,gestational hypertension,...,NaN,NaN,NaN,NaN,"IVF, immigrated at 30 weeks",95833,<NA>,<NA>,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,2023,N,8093931,Term,Y,Singleton,N,White,Y,gestational hypertension,...,NaN,NaN,NaN,NaN,NaN,95842,2745,958422745,True,False
349,2023,N,8105947,Term,Y,Singleton,Y,Asian,Y,gestational hypertension,...,NaN,NaN,NaN,NaN,NaN,95742,6626,957426626,False,True
350,2023,N,7662725,Term,N,Singleton,Y,White,Y,chronic hypertension,...,NaN,NaN,NaN,NaN,NaN,95616,138,956160138,True,False
351,2023,N,8351519,Term,Y,Singleton,N,White,Y,gestational hypertension,...,NaN,NaN,NaN,NaN,NaN,95670,2952,956702952,False,True
352,2023,"Y, 2023",8299905,Term,Y,Singleton,Y,Hispanic,Y,preeclampsia with SF,...,NaN,NaN,NaN,NaN,NaN,95691,2945,956912945,False,True

In [28]:
"""
 ,Racial/Ethnicity,'Type of DM','Term/Preterm', 'Induction',
'Singleton/Multiple',â€™Multipsâ€™,'HDP Diagnosis (Y/N)',
'HDP Diagnosis (delivery episode)'
"""

temp_one_hot = pd.get_dummies(maindata['Racial/Ethnicity'])
maindata = maindata.drop('Racial/Ethnicity',axis = 1)
# Join the encoded df
maindata = maindata.join(temp_one_hot,rsuffix="_race/eth")

temp_one_hot = pd.get_dummies(maindata['Type of DM'])
maindata = maindata.drop('Type of DM',axis = 1)
# Join the encoded df
maindata = maindata.join(temp_one_hot,lsuffix='_DM')
maindata

temp_one_hot = pd.get_dummies(maindata['Term/Preterm'])
maindata = maindata.drop('Term/Preterm',axis = 1)
# Join the encoded df
maindata = maindata.join(temp_one_hot)
maindata

,Fiscal Year,ECG,Mutated MRN,Induction,Singleton/Multiple,Multips,HDP Diagnosis (Y/N),HDP Diagnosis (delivery episode),Diabetes (Y/N),Meth/Cocaine use(Y/N),...,Other,White,A1GDM,A2GDM,N,T1,T1DM,T2DM,Preterm,Term
0,2021,"Y, 4 month prior to del",7887439,Y,Singleton,Y,Y,gestational hypertension,Y,N,...,False,False,False,True,False,False,False,False,False,True
1,2021,"Y, in labor",2392172,Y,Singleton,Y,Y,preeclampsia with SF,N,N,...,False,True,False,False,False,False,False,False,False,True
2,2021,"Y, postpartum",1252118,Y,Singleton,Y,N,No Episode,N,N,...,False,True,False,False,False,False,False,False,False,True
3,2021,N,7872701,Y,Singleton,Y,Y,superimposed with SF,Y,N,...,False,False,False,True,False,False,False,False,False,True
4,2021,N,7954972,N,Singleton,Y,Y,gestational hypertension,Y,N,...,False,False,False,True,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,2023,N,8093931,Y,Singleton,N,Y,gestational hypertension,Y,N,...,False,True,False,True,False,False,False,False,False,True
349,2023,N,8105947,Y,Singleton,Y,Y,gestational hypertension,Y,N,...,False,False,False,True,False,False,False,False,False,True
350,2023,N,7662725,N,Singleton,Y,Y,chronic hypertension,N,N,...,False,True,False,False,False,False,False,False,False,True
351,2023,N,8351519,Y,Singleton,N,Y,gestational hypertension,N,N,...,False,True,False,False,False,False,False,False,False,True
352,2023,"Y, 2023",8299905,Y,Singleton,Y,Y,preeclampsia with SF,N,N,...,False,False,False,False,False,False,False,False,False,True

In [29]:
maindata.columns
maindata = maindata.rename(columns={'N': 'N_Diabetes'})

In [30]:
maindata.columns

Index(['Fiscal Year', 'ECG', 'Mutated MRN', 'Induction', 'Singleton/Multiple',
       'Multips', 'HDP Diagnosis (Y/N)', 'HDP Diagnosis (delivery episode)',
       'Diabetes (Y/N)', 'Meth/Cocaine use(Y/N)', 'Readmitted (Y/N)',
       'HDP Diagnosis (readmission episode) or NA', 'Delivery Date',
       'Readmission date', 'Age', 'BMI prepregnancy', 'BMI close to delivery',
       'On HDP meds at dc from birth episode (Y/N)', 'If Y, how many?',
       'Betablocker dose at dc', 'Nifedipine dose at dc', 'Other meds at dc',
       'Notes', 'ZIPCODE', 'Zipcode_last4', 'ZIP_4', 'c-section', 'vaginal',
       'AA', 'Asian', 'Declined', 'Hispanic', 'Middle Eastern',
       'Mixed (Asian, White)', 'Mixed (Asian, White, AA)', 'Other', 'White',
       'A1GDM', 'A2GDM', 'N_Diabetes', 'T1', 'T1DM', 'T2DM', 'Preterm',
       'Term'],
      dtype='object')

In [31]:


temp_one_hot = pd.get_dummies(maindata['Induction'])
maindata = maindata.drop('Induction',axis = 1)
# Join the encoded df
maindata = maindata.join(temp_one_hot,lsuffix='_Induction')
maindata

temp_one_hot = pd.get_dummies(maindata['Singleton/Multiple'])
maindata = maindata.drop('Singleton/Multiple',axis = 1)
# Join the encoded df
maindata = maindata.join(temp_one_hot)
maindata

temp_one_hot = pd.get_dummies(maindata['Multips'])
maindata = maindata.drop('Multips',axis = 1)
# Join the encoded df
maindata = maindata.join(temp_one_hot,rsuffix='_Multips')
maindata

temp_one_hot = pd.get_dummies(maindata['HDP Diagnosis (Y/N)'])
maindata = maindata.drop('HDP Diagnosis (Y/N)',axis = 1)
# Join the encoded df
maindata = maindata.join(temp_one_hot,rsuffix='_HDP Diag')
maindata

temp_one_hot = pd.get_dummies(maindata['HDP Diagnosis (delivery episode)'])
maindata = maindata.drop('HDP Diagnosis (delivery episode)',axis = 1)
# Join the encoded df
maindata = maindata.join(temp_one_hot)
maindata

,Fiscal Year,ECG,Mutated MRN,Diabetes (Y/N),Meth/Cocaine use(Y/N),Readmitted (Y/N),HDP Diagnosis (readmission episode) or NA,Delivery Date,Readmission date,Age,...,Y_HDP Diag,No Episode,chronic hypertension,gestational hypertension,none,preeclampsia with SF,preeclampsia without SF,superimposed with SF,superimposed with SF w/ SF,superimposed without SF
0,2021,"Y, 4 month prior to del",7887439,Y,N,Y,preeclampsia with SF,2021-07-04,2021-07-08 00:00:00,38.0,...,True,False,False,True,False,False,False,False,False,False
1,2021,"Y, in labor",2392172,N,N,Y,preeclampsia with SF,2021-07-06,2021-07-12 00:00:00,34.0,...,True,False,False,False,False,True,False,False,False,False
2,2021,"Y, postpartum",1252118,N,N,Y,preeclampsia with SF,2021-07-22,2021-07-29 00:00:00,31.0,...,False,True,False,False,False,False,False,False,False,False
3,2021,N,7872701,Y,N,Y,superimposed with SF,2021-08-03,2021-08-12 00:00:00,33.0,...,True,False,False,False,False,False,False,True,False,False
4,2021,N,7954972,Y,N,Y,preeclampsia with SF,2021-08-06,2021-08-14 00:00:00,44.0,...,True,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,2023,N,8093931,Y,N,N,NaN,2023-05-28,NaN,29.0,...,True,False,False,True,False,False,False,False,False,False
349,2023,N,8105947,Y,N,N,NaN,2023-05-30,NaN,38.0,...,True,False,False,True,False,False,False,False,False,False
350,2023,N,7662725,N,N,N,NaN,2023-05-30,NaN,29.0,...,True,False,True,False,False,False,False,False,False,False
351,2023,N,8351519,N,N,N,NaN,2023-05-31,NaN,37.0,...,True,False,False,True,False,False,False,False,False,False
352,2023,"Y, 2023",8299905,N,N,N,NaN,2023-05-31,NaN,44.0,...,True,False,False,False,False,True,False,False,False,False

In [32]:
maindata.columns

Index(['Fiscal Year', 'ECG', 'Mutated MRN', 'Diabetes (Y/N)',
       'Meth/Cocaine use(Y/N)', 'Readmitted (Y/N)',
       'HDP Diagnosis (readmission episode) or NA', 'Delivery Date',
       'Readmission date', 'Age', 'BMI prepregnancy', 'BMI close to delivery',
       'On HDP meds at dc from birth episode (Y/N)', 'If Y, how many?',
       'Betablocker dose at dc', 'Nifedipine dose at dc', 'Other meds at dc',
       'Notes', 'ZIPCODE', 'Zipcode_last4', 'ZIP_4', 'c-section', 'vaginal',
       'AA', 'Asian', 'Declined', 'Hispanic', 'Middle Eastern',
       'Mixed (Asian, White)', 'Mixed (Asian, White, AA)', 'Other', 'White',
       'A1GDM', 'A2GDM', 'N_Diabetes', 'T1', 'T1DM', 'T2DM', 'Preterm', 'Term',
       'N', 'Y', 'Multiple', 'Singleton', 'N_Multips', 'Y_Multips',
       'N_HDP Diag', 'Y_HDP Diag', 'No Episode', 'chronic hypertension',
       'gestational hypertension', 'none', 'preeclampsia with SF',
       'preeclampsia without SF', 'superimposed with SF',
       'superimposed with SF w/ SF', 'superimposed without SF'],
      dtype='object')

In [33]:
maindata.columns
maindata = maindata.rename(columns={'N': 'No Induction'})
maindata = maindata.rename(columns={'Y': 'Yes Induction'})

maindata.loc[maindata['ECG'].str.contains('Y')==True,'ECG'] = 'Y'

temp_one_hot = pd.get_dummies(maindata['ECG'])
maindata = maindata.drop('ECG',axis = 1)
# Join the encoded df
maindata = maindata.join(temp_one_hot,rsuffix='_ECG')
maindata = maindata.rename(columns={'N': 'N_ECG'})
maindata = maindata.rename(columns={'Y': 'Y_ECG'})
maindata

maindata.columns

Index(['Fiscal Year', 'Mutated MRN', 'Diabetes (Y/N)', 'Meth/Cocaine use(Y/N)',
       'Readmitted (Y/N)', 'HDP Diagnosis (readmission episode) or NA',
       'Delivery Date', 'Readmission date', 'Age', 'BMI prepregnancy',
       'BMI close to delivery', 'On HDP meds at dc from birth episode (Y/N)',
       'If Y, how many?', 'Betablocker dose at dc', 'Nifedipine dose at dc',
       'Other meds at dc', 'Notes', 'ZIPCODE', 'Zipcode_last4', 'ZIP_4',
       'c-section', 'vaginal', 'AA', 'Asian', 'Declined', 'Hispanic',
       'Middle Eastern', 'Mixed (Asian, White)', 'Mixed (Asian, White, AA)',
       'Other', 'White', 'A1GDM', 'A2GDM', 'N_Diabetes', 'T1', 'T1DM', 'T2DM',
       'Preterm', 'Term', 'No Induction', 'Yes Induction', 'Multiple',
       'Singleton', 'N_Multips', 'Y_Multips', 'N_HDP Diag', 'Y_HDP Diag',
       'No Episode', 'chronic hypertension', 'gestational hypertension',
       'none', 'preeclampsia with SF', 'preeclampsia without SF',
       'superimposed with SF', 'superimposed with SF w/ SF',
       'superimposed without SF', 'N_ECG', 'Y_ECG'],
      dtype='object')

In [34]:
"""Diabetes (Y/N)','Meth/Cocaine use(Y/N)'"""
maindata['Diabetes (Y/N)'].unique()
diab_mapper = {'Y':1 , 'N':0}
maindata['Diabetes (Y/N)'] = maindata['Diabetes (Y/N)'].replace(diab_mapper)
print(maindata['Diabetes (Y/N)'])

0      1
1      0
2      0
3      1
4      1
      ..
348    1
349    1
350    0
351    0
352    0
Name: Diabetes (Y/N), Length: 345, dtype: int64

In [35]:
"""Diabetes (Y/N)','Meth/Cocaine use(Y/N)'"""
maindata['Meth/Cocaine use(Y/N)'].unique()
meth_mapper = {'Y':1 , 'N':0}
maindata['Meth/Cocaine use(Y/N)'] = maindata['Meth/Cocaine use(Y/N)'].replace(meth_mapper)
print(maindata['Meth/Cocaine use(Y/N)'])

0      0
1      0
2      0
3      0
4      0
      ..
348    0
349    0
350    0
351    0
352    0
Name: Meth/Cocaine use(Y/N), Length: 345, dtype: int64

In [36]:
maindata['On HDP meds at dc from birth episode (Y/N)'].value_counts()
hdpmeds_mapper = {'Y':1 , 'N':0}
maindata['On HDP meds at dc from birth episode (Y/N)'] = maindata['On HDP meds at dc from birth episode (Y/N)'].replace(hdpmeds_mapper)
print(maindata['On HDP meds at dc from birth episode (Y/N)'])

0      0.0
1      1.0
2      0.0
3      1.0
4      0.0
      ...
348    0.0
349    0.0
350    0.0
351    0.0
352    0.0
Name: On HDP meds at dc from birth episode (Y/N), Length: 345, dtype: float64

In [37]:
maindata.columns

Index(['Fiscal Year', 'Mutated MRN', 'Diabetes (Y/N)', 'Meth/Cocaine use(Y/N)',
       'Readmitted (Y/N)', 'HDP Diagnosis (readmission episode) or NA',
       'Delivery Date', 'Readmission date', 'Age', 'BMI prepregnancy',
       'BMI close to delivery', 'On HDP meds at dc from birth episode (Y/N)',
       'If Y, how many?', 'Betablocker dose at dc', 'Nifedipine dose at dc',
       'Other meds at dc', 'Notes', 'ZIPCODE', 'Zipcode_last4', 'ZIP_4',
       'c-section', 'vaginal', 'AA', 'Asian', 'Declined', 'Hispanic',
       'Middle Eastern', 'Mixed (Asian, White)', 'Mixed (Asian, White, AA)',
       'Other', 'White', 'A1GDM', 'A2GDM', 'N_Diabetes', 'T1', 'T1DM', 'T2DM',
       'Preterm', 'Term', 'No Induction', 'Yes Induction', 'Multiple',
       'Singleton', 'N_Multips', 'Y_Multips', 'N_HDP Diag', 'Y_HDP Diag',
       'No Episode', 'chronic hypertension', 'gestational hypertension',
       'none', 'preeclampsia with SF', 'preeclampsia without SF',
       'superimposed with SF', 'superimposed with SF w/ SF',
       'superimposed without SF', 'N_ECG', 'Y_ECG'],
      dtype='object')

In [38]:
maindata.to_csv("zipcode_coded.csv", index=False)

In [35]:
sdoh_data = pd.ExcelFile('SDOH_2020_ZIPCODE_1_0.xlsx')

# Now you can list all sheets in the file
sdoh_data.sheet_names
# ['house', 'house_extra', ...]

['Layout', 'Data']

In [36]:

# to read just one sheet to dataframe:
sdoh_datasheet = pd.read_excel(sdoh_data, sheet_name="Data")

In [37]:
sdoh_datasheet.columns

Index(['YEAR', 'STATEFIPS', 'ZIPCODE', 'ZCTA', 'STATE', 'REGION', 'TERRITORY',
       'POINT_ZIP', 'ACS_TOT_POP_WT_ZC', 'ACS_TOT_POP_US_ABOVE1_ZC',
       ...
       'CEN_POPDENSITY_ZC', 'HIFLD_DIST_UC_ZP', 'POS_DIST_ED_ZP',
       'POS_DIST_MEDSURG_ICU_ZP', 'POS_DIST_TRAUMA_ZP', 'POS_DIST_PED_ICU_ZP',
       'POS_DIST_OBSTETRICS_ZP', 'POS_DIST_CLINIC_ZP', 'POS_DIST_ALC_ZP',
       'CEN_AIAN_NH_IND'],
      dtype='object', length=327)

In [38]:
sdoh_datasheet.describe()

,YEAR,STATEFIPS,ZIPCODE,ZCTA,TERRITORY,POINT_ZIP,ACS_TOT_POP_WT_ZC,ACS_TOT_POP_US_ABOVE1_ZC,ACS_TOT_POP_ABOVE5_ZC,ACS_TOT_POP_ABOVE15_ZC,...,CEN_POPDENSITY_ZC,HIFLD_DIST_UC_ZP,POS_DIST_ED_ZP,POS_DIST_MEDSURG_ICU_ZP,POS_DIST_TRAUMA_ZP,POS_DIST_PED_ICU_ZP,POS_DIST_OBSTETRICS_ZP,POS_DIST_CLINIC_ZP,POS_DIST_ALC_ZP,CEN_AIAN_NH_IND
count,41051.0,41051.000000,41051.000000,41011.000000,41051.000000,41051.000000,40988.000000,40817.000000,40988.000000,40988.000000,...,33528.000000,39419.000000,39442.000000,39440.000000,39438.000000,39387.000000,39442.000000,39447.000000,39442.000000,40988.000000
mean,2020.0,29.489732,49592.014933,49536.186291,0.004848,0.220141,13172.665561,12965.618615,12386.567190,10775.334464,...,1653.495437,17.130717,8.283206,10.500076,18.243923,30.600796,10.137165,6.218493,18.150268,0.079413
std,0.0,15.772151,27946.082600,27925.175185,0.069457,0.414346,16796.312827,16566.501750,15735.362972,13610.648691,...,6125.808756,25.259811,11.313635,16.649916,20.330958,31.428633,12.292224,9.657878,21.478753,0.270386
min,2020.0,1.000000,501.000000,601.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2020.0,17.000000,26120.500000,26033.500000,0.000000,0.000000,1065.000000,1047.000000,1009.000000,883.000000,...,29.327500,2.750000,2.030000,2.380000,5.492500,9.740000,2.690000,1.400000,4.320000,0.000000
50%,2020.0,29.000000,48846.000000,48818.000000,0.000000,0.000000,4963.000000,4858.000000,4711.000000,4124.000000,...,120.455000,10.530000,6.350000,7.420000,13.750000,24.370000,7.810000,4.390000,12.750000,0.000000
75%,2020.0,42.000000,72957.500000,72940.500000,0.000000,0.000000,20948.250000,20605.000000,19806.000000,17274.000000,...,1113.695000,23.225000,11.420000,13.760000,25.290000,42.335000,14.000000,8.510000,24.790000,0.000000
max,2020.0,78.000000,99950.000000,99929.000000,1.000000,1.000000,126310.000000,125181.000000,116812.000000,92050.000000,...,152700.540000,492.720000,469.880000,478.530000,485.830000,497.690000,469.880000,391.690000,469.880000,1.000000

In [39]:
sdoh_datasheet.head()

,YEAR,STATEFIPS,ZIPCODE,ZCTA,STATE,REGION,TERRITORY,POINT_ZIP,ACS_TOT_POP_WT_ZC,ACS_TOT_POP_US_ABOVE1_ZC,...,CEN_POPDENSITY_ZC,HIFLD_DIST_UC_ZP,POS_DIST_ED_ZP,POS_DIST_MEDSURG_ICU_ZP,POS_DIST_TRAUMA_ZP,POS_DIST_PED_ICU_ZP,POS_DIST_OBSTETRICS_ZP,POS_DIST_CLINIC_ZP,POS_DIST_ALC_ZP,CEN_AIAN_NH_IND
0,2020,15,96759,NaN,Hawaii,NaN,0,1,NaN,NaN,...,NaN,7.41,4.61,4.61,10.44,16.30,10.44,3.98,10.44,NaN
1,2020,2,99675,NaN,Alaska,NaN,0,1,NaN,NaN,...,NaN,205.60,209.98,210.08,211.62,210.08,209.98,39.64,210.73,NaN
2,2020,41,97010,NaN,Oregon,NaN,0,0,NaN,NaN,...,NaN,12.98,16.76,16.76,25.34,29.23,16.76,12.49,24.05,NaN
3,2020,6,93928,NaN,California,NaN,0,1,NaN,NaN,...,NaN,26.02,19.44,19.44,56.02,96.97,19.44,19.17,53.74,NaN
4,2020,6,95836,NaN,California,NaN,0,0,NaN,NaN,...,NaN,6.58,10.30,10.30,12.87,12.32,12.32,9.29,10.30,NaN

In [40]:
sdoh_datasheet[sdoh_datasheet['STATE']=='California']

,YEAR,STATEFIPS,ZIPCODE,ZCTA,STATE,REGION,TERRITORY,POINT_ZIP,ACS_TOT_POP_WT_ZC,ACS_TOT_POP_US_ABOVE1_ZC,...,CEN_POPDENSITY_ZC,HIFLD_DIST_UC_ZP,POS_DIST_ED_ZP,POS_DIST_MEDSURG_ICU_ZP,POS_DIST_TRAUMA_ZP,POS_DIST_PED_ICU_ZP,POS_DIST_OBSTETRICS_ZP,POS_DIST_CLINIC_ZP,POS_DIST_ALC_ZP,CEN_AIAN_NH_IND
3,2020,6,93928,NaN,California,NaN,0,1,NaN,NaN,...,NaN,26.02,19.44,19.44,56.02,96.97,19.44,19.17,53.74,NaN
4,2020,6,95836,NaN,California,NaN,0,0,NaN,NaN,...,NaN,6.58,10.30,10.30,12.87,12.32,12.32,9.29,10.30,NaN
10,2020,6,91023,NaN,California,NaN,0,1,NaN,NaN,...,NaN,5.72,4.29,4.29,7.92,7.92,6.47,6.86,4.29,NaN
13,2020,6,93581,NaN,California,NaN,0,1,NaN,NaN,...,NaN,33.30,0.24,33.29,33.29,35.91,33.29,0.83,35.69,NaN
16,2020,6,93530,NaN,California,NaN,0,1,NaN,NaN,...,NaN,78.62,20.67,41.74,84.90,83.12,20.67,20.69,76.99,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39441,2020,6,96152,96150.0,California,West,0,1,30369.0,30169.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
39442,2020,6,96151,96150.0,California,West,0,1,30369.0,30169.0,...,NaN,2.76,2.88,2.88,2.88,2.88,2.88,2.81,20.82,0.0
39443,2020,6,96150,96150.0,California,West,0,0,30369.0,30169.0,...,NaN,0.65,0.56,0.56,0.56,0.56,0.56,0.50,22.68,0.0
39444,2020,6,96161,96161.0,California,West,0,0,18782.0,18658.0,...,NaN,1.12,1.05,1.05,24.59,24.59,1.05,0.99,23.58,0.0
39445,2020,6,96160,96161.0,California,West,0,1,18782.0,18658.0,...,NaN,1.06,0.94,0.94,24.73,24.73,0.94,0.91,23.25,0.0

In [41]:
sdoh_datasheet[sdoh_datasheet['STATE']=='California'].describe()

,YEAR,STATEFIPS,ZIPCODE,ZCTA,TERRITORY,POINT_ZIP,ACS_TOT_POP_WT_ZC,ACS_TOT_POP_US_ABOVE1_ZC,ACS_TOT_POP_ABOVE5_ZC,ACS_TOT_POP_ABOVE15_ZC,...,CEN_POPDENSITY_ZC,HIFLD_DIST_UC_ZP,POS_DIST_ED_ZP,POS_DIST_MEDSURG_ICU_ZP,POS_DIST_TRAUMA_ZP,POS_DIST_PED_ICU_ZP,POS_DIST_OBSTETRICS_ZP,POS_DIST_CLINIC_ZP,POS_DIST_ALC_ZP,CEN_AIAN_NH_IND
count,2585.0,2585.0,2585.000000,2578.000000,2585.0,2585.000000,2578.000000,2578.000000,2578.000000,2578.000000,...,0.0,2449.000000,2449.000000,2449.000000,2449.000000,2449.000000,2449.000000,2449.000000,2449.000000,2578.000000
mean,2020.0,6.0,93472.563636,93502.135376,0.0,0.327660,27093.678433,26800.521334,25433.558185,22028.567106,...,NaN,9.022050,5.654418,7.042364,13.567432,21.001311,6.448599,3.979771,14.552883,0.072537
std,0.0,0.0,1792.517535,1825.187593,0.0,0.469451,23241.920386,22972.072254,21695.088342,18544.889841,...,NaN,15.237648,7.587959,10.910870,15.189825,24.046998,8.415190,5.365142,19.172607,0.259425
min,2020.0,6.0,90001.000000,90001.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010000,0.000000,0.000000
25%,2020.0,6.0,92117.000000,92108.000000,0.0,0.000000,4639.750000,4570.000000,4293.000000,3802.250000,...,NaN,1.140000,1.170000,1.150000,3.360000,4.090000,1.370000,0.890000,2.490000,0.000000
50%,2020.0,6.0,93543.000000,93536.000000,0.0,0.000000,25449.500000,25193.000000,23948.000000,20606.000000,...,NaN,2.480000,2.390000,2.450000,7.290000,9.800000,2.820000,2.270000,5.760000,0.000000
75%,2020.0,6.0,95159.000000,95250.500000,0.0,1.000000,41534.000000,40966.000000,38809.750000,33922.000000,...,NaN,9.430000,7.100000,8.030000,18.680000,31.730000,8.420000,5.000000,19.400000,0.000000
max,2020.0,6.0,96162.000000,96161.000000,0.0,1.000000,110750.000000,109734.000000,102694.000000,84073.000000,...,NaN,95.990000,66.550000,93.900000,117.010000,117.760000,66.550000,64.270000,129.710000,1.000000

In [71]:
from copy import deepcopy

cal_sdoh = deepcopy(sdoh_datasheet[sdoh_datasheet['STATE']=='California'])
cal_sdoh[cal_sdoh['ZCTA']!=cal_sdoh['ZIPCODE']]

,YEAR,STATEFIPS,ZIPCODE,ZCTA,STATE,REGION,TERRITORY,POINT_ZIP,ACS_TOT_POP_WT_ZC,ACS_TOT_POP_US_ABOVE1_ZC,...,CEN_POPDENSITY_ZC,HIFLD_DIST_UC_ZP,POS_DIST_ED_ZP,POS_DIST_MEDSURG_ICU_ZP,POS_DIST_TRAUMA_ZP,POS_DIST_PED_ICU_ZP,POS_DIST_OBSTETRICS_ZP,POS_DIST_CLINIC_ZP,POS_DIST_ALC_ZP,CEN_AIAN_NH_IND
3,2020,6,93928,NaN,California,NaN,0,1,NaN,NaN,...,NaN,26.02,19.44,19.44,56.02,96.97,19.44,19.17,53.74,NaN
4,2020,6,95836,NaN,California,NaN,0,0,NaN,NaN,...,NaN,6.58,10.30,10.30,12.87,12.32,12.32,9.29,10.30,NaN
10,2020,6,91023,NaN,California,NaN,0,1,NaN,NaN,...,NaN,5.72,4.29,4.29,7.92,7.92,6.47,6.86,4.29,NaN
13,2020,6,93581,NaN,California,NaN,0,1,NaN,NaN,...,NaN,33.30,0.24,33.29,33.29,35.91,33.29,0.83,35.69,NaN
16,2020,6,93530,NaN,California,NaN,0,1,NaN,NaN,...,NaN,78.62,20.67,41.74,84.90,83.12,20.67,20.69,76.99,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39439,2020,6,96155,96150.0,California,West,0,1,30369.0,30169.0,...,NaN,4.41,4.18,4.18,4.18,4.18,4.18,4.20,27.16,0.0
39440,2020,6,96154,96150.0,California,West,0,1,30369.0,30169.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
39441,2020,6,96152,96150.0,California,West,0,1,30369.0,30169.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
39442,2020,6,96151,96150.0,California,West,0,1,30369.0,30169.0,...,NaN,2.76,2.88,2.88,2.88,2.88,2.88,2.81,20.82,0.0
39445,2020,6,96160,96161.0,California,West,0,1,18782.0,18658.0,...,NaN,1.06,0.94,0.94,24.73,24.73,0.94,0.91,23.25,0.0

In [72]:
cal_sdoh=cal_sdoh.reset_index(drop=True)

In [73]:
cols_to_use ="""YEAR
STATEFIPS
ZIPCODE
ZCTA
STATE
REGION
ACS_TOT_POP_WT_ZC
ACS_TOT_POP_US_ABOVE1_ZC
ACS_TOT_POP_ABOVE5_ZC
ACS_TOT_POP_ABOVE15_ZC
ACS_TOT_POP_ABOVE16_ZC
ACS_TOT_POP_16_19_ZC
ACS_TOT_POP_ABOVE25_ZC
ACS_TOT_OWN_CHILD_BELOW17_ZC
ACS_TOT_WORKER_HH_ZC
ACS_TOT_CIVIL_EMPLOY_POP_ZC
ACS_TOT_CIVIL_NONINST_POP_POV_ZC
ACS_TOT_POP_POV_ZC
ACS_TOT_GRANDCHILDREN_GP_ZC
ACS_TOT_HU_ZC
ACS_TOT_HH_ZC
ACS_AVG_HH_SIZE_ZC
ACS_PCT_FEMALE_ZC
ACS_PCT_MALE_ZC
ACS_PCT_CTZ_US_BORN_ZC
ACS_PCT_FOREIGN_BORN_ZC
ACS_PCT_NON_CITIZEN_ZC
ACS_PCT_API_LANG_ZC
ACS_PCT_ENGL_NOT_ALL_ZC
ACS_PCT_ENGL_NOT_WELL_ZC
ACS_PCT_ENGLISH_ZC
ACS_PCT_HH_LIMIT_ENGLISH_ZC
ACS_PCT_OTH_EURP_ZC
ACS_PCT_OTH_LANG_ZC
ACS_PCT_SPANISH_ZC
ACS_MEDIAN_AGE_ZC
ACS_MEDIAN_AGE_FEMALE_ZC
ACS_PCT_AGE_0_4_ZC
ACS_PCT_AGE_5_9_ZC
ACS_PCT_AGE_10_14_ZC
ACS_PCT_AGE_15_17_ZC
ACS_PCT_AGE_0_17_ZC
ACS_PCT_AGE_18_29_ZC
ACS_PCT_AGE_18_44_ZC
ACS_PCT_AGE_30_44_ZC
ACS_PCT_AGE_45_64_ZC
ACS_PCT_HH_NO_COMP_DEV_ZC
ACS_PCT_HH_SMARTPHONE_ZC
ACS_PCT_HH_SMARTPHONE_ONLY_ZC
ACS_PCT_HH_TABLET_ZC
ACS_PCT_HH_TABLET_ONLY_ZC
ACS_PCT_HH_PC_ZC
ACS_PCT_HH_PC_ONLY_ZC
ACS_PCT_HH_OTHER_COMP_ZC
ACS_PCT_HH_OTHER_COMP_ONLY_ZC
ACS_PCT_HH_INTERNET_ZC
ACS_PCT_HH_INTERNET_NO_SUBS_ZC
ACS_PCT_HH_CELLULAR_ZC
ACS_PCT_HH_CELLULAR_ONLY_ZC
ACS_PCT_HH_NO_INTERNET_ZC
ACS_PCT_HH_SAT_INTERNET_ZC
ACS_PCT_HH_DIAL_INTERNET_ONLY_ZC
ACS_PCT_CHILD_1FAM_ZC
ACS_PCT_HH_KID_1PRNT_ZC
ACS_PCT_DIVORCED_F_ZC
ACS_PCT_MARRIED_SP_AB_F_ZC
ACS_PCT_MARRIED_SP_PR_F_ZC
ACS_PCT_NVR_MARRIED_F_ZC
ACS_PCT_POP_SAME_SEX_UNMRD_P_ZC
ACS_PCT_POP_SAME_SEX_SPOUSE_ZC
ACS_GINI_INDEX_ZC
ACS_MDN_GRNDPRNT_NO_PRNT_INC_ZC
ACS_MDN_GRNDPRNT_INC_ZC
ACS_MEDIAN_HH_INC_AIAN_ZC
ACS_MEDIAN_HH_INC_ASIAN_ZC
ACS_MEDIAN_HH_INC_BLACK_ZC
ACS_MEDIAN_HH_INC_HISP_ZC
ACS_MEDIAN_HH_INC_MULTI_ZC
ACS_MEDIAN_HH_INC_NHPI_ZC
ACS_MEDIAN_HH_INC_OTHER_ZC
ACS_MEDIAN_HH_INC_WHITE_ZC
ACS_MEDIAN_HH_INC_ZC
ACS_MEDIAN_INC_F_ZC
ACS_MEDIAN_INC_M_ZC
ACS_PCT_INC50_ABOVE65_ZC
ACS_PCT_INC50_BELOW17_ZC
ACS_PCT_HEALTH_INC_BELOW137_ZC
ACS_PCT_HEALTH_INC_138_199_ZC
ACS_PCT_HEALTH_INC_200_399_ZC
ACS_PCT_HEALTH_INC_ABOVE400_ZC
ACS_PCT_HH_INC_10000_ZC
ACS_PCT_HH_INC_100000_ZC
ACS_PCT_HH_INC_14999_ZC
ACS_PCT_HH_INC_24999_ZC
ACS_PCT_HH_INC_49999_ZC
ACS_PCT_HH_INC_99999_ZC
ACS_PCT_INC50_ZC
ACS_PCT_NONVET_POV_18_64_ZC
ACS_PCT_VET_POV_18_64_ZC
ACS_PCT_PERSON_INC_100_124_ZC
ACS_PCT_PERSON_INC_125_199_ZC
ACS_PCT_PERSON_INC_ABOVE200_ZC
ACS_PCT_PERSON_INC_BELOW99_ZC
ACS_PER_CAPITA_INC_ZC
ACS_PCT_POV_AIAN_ZC
ACS_PCT_POV_ASIAN_ZC
ACS_PCT_POV_BLACK_ZC
ACS_PCT_POV_HISPANIC_ZC
ACS_PCT_POV_MULTI_ZC
ACS_PCT_POV_NHPI_ZC
ACS_PCT_POV_OTHER_ZC
ACS_PCT_POV_WHITE_ZC
ACS_PCT_HH_1FAM_FOOD_STMP_ZC
ACS_PCT_HH_FOOD_STMP_ZC
ACS_PCT_HH_FOOD_STMP_BLW_POV_ZC
ACS_PCT_HH_NO_FD_STMP_BLW_POV_ZC
ACS_PCT_HH_PUB_ASSIST_ZC
ACS_PCT_COLLEGE_ASSOCIATE_DGR_ZC
ACS_PCT_BACHELOR_DGR_ZC
ACS_PCT_NO_WORK_NO_SCHL_16_19_ZC
ACS_PCT_GRADUATE_DGR_ZC
ACS_PCT_HS_GRADUATE_ZC
ACS_PCT_LT_HS_ZC
ACS_PCT_POSTHS_ED_ZC
ACS_PCT_VET_BACHELOR_ZC
ACS_PCT_VET_COLLEGE_ZC
ACS_PCT_VET_HS_ZC
ACS_MEDIAN_HOME_VALUE_ZC
ACS_MEDIAN_RENT_ZC
ACS_MDN_OWNER_COST_MORTGAGE_ZC
ACS_MDN_OWNER_COST_NO_MORTG_ZC
ACS_MEDIAN_YEAR_BUILT_ZC
ACS_PCT_10UNITS_ZC
ACS_PCT_1UP_OWNER_1ROOM_ZC
ACS_PCT_1UP_PERS_1ROOM_ZC
ACS_PCT_1UP_RENT_1ROOM_ZC
ACS_PCT_RENTER_HU_COST_30PCT_ZC
ACS_PCT_RENTER_HU_COST_50PCT_ZC
ACS_PCT_RENTER_HU_ZC
ACS_PCT_RENTER_HU_CHILD_ZC
ACS_PCT_VACANT_HU_ZC
ACS_PCT_HU_NO_VEH_ZC
ACS_PCT_PUB_COMMT_15MIN_ZC
ACS_PCT_PUB_COMMT_29MIN_ZC
ACS_PCT_PUB_COMMT_59MIN_ZC
ACS_PCT_PUB_COMMT_60MINUP_ZC
ACS_PCT_PUBL_TRANSIT_ZC
ACS_PCT_TAXICAB_2WORK_ZC
ACS_PCT_WALK_2WORK_ZC
ACS_PCT_WORK_NO_CAR_ZC
ACS_PCT_MEDICAID_ANY_ZC
ACS_PCT_MEDICAID_ANY_BELOW64_ZC
ACS_PCT_MEDICARE_ONLY_ZC
ACS_PCT_OTHER_INS_ZC
ACS_PCT_PVT_EMPL_DRCT_ZC
ACS_PCT_PVT_EMPL_DRCT_BELOW64_ZC
ACS_PCT_PRIVATE_ANY_ZC
ACS_PCT_PRIVATE_ANY_BELOW64_ZC
ACS_PCT_PRIVATE_EMPL_ZC
ACS_PCT_PRIVATE_EMPL_BELOW64_ZC
ACS_PCT_PRIVATE_MDCR_ZC
ACS_PCT_PRIVATE_MDCR_35_64_ZC
ACS_PCT_PRIVATE_OTHER_ZC
ACS_PCT_PRIVATE_OTHER_BELOW64_ZC
ACS_PCT_PRIVATE_SELF_ZC
ACS_PCT_PRIVATE_SELF_BELOW64_ZC
ACS_PCT_PUBLIC_ONLY_ZC
ACS_PCT_PUBLIC_OTHER_ZC
ACS_PCT_PUBLIC_OTHER_BELOW64_ZC
ACS_PCT_SELF_MDCR_ABOVE35_ZC
ACS_PCT_TRICARE_VA_ZC
ACS_PCT_TRICARE_VA_BELOW64_ZC
ACS_PCT_UNINSURED_ZC
ACS_PCT_UNINSURED_BELOW64_ZC
CEN_AREALAND_SQM_ZC
CEN_POPDENSITY_ZC
HIFLD_DIST_UC_ZP
POS_DIST_ED_ZP
POS_DIST_MEDSURG_ICU_ZP
POS_DIST_TRAUMA_ZP
POS_DIST_PED_ICU_ZP
POS_DIST_OBSTETRICS_ZP
POS_DIST_CLINIC_ZP
POS_DIST_ALC_ZP
CEN_AIAN_NH_IND"""

In [74]:
cols_to_use =cols_to_use.split("\n")
cols_to_use

['YEAR',
 'STATEFIPS',
 'ZIPCODE',
 'ZCTA',
 'STATE',
 'REGION',
 'ACS_TOT_POP_WT_ZC',
 'ACS_TOT_POP_US_ABOVE1_ZC',
 'ACS_TOT_POP_ABOVE5_ZC',
 'ACS_TOT_POP_ABOVE15_ZC',
 'ACS_TOT_POP_ABOVE16_ZC',
 'ACS_TOT_POP_16_19_ZC',
 'ACS_TOT_POP_ABOVE25_ZC',
 'ACS_TOT_OWN_CHILD_BELOW17_ZC',
 'ACS_TOT_WORKER_HH_ZC',
 'ACS_TOT_CIVIL_EMPLOY_POP_ZC',
 'ACS_TOT_CIVIL_NONINST_POP_POV_ZC',
 'ACS_TOT_POP_POV_ZC',
 'ACS_TOT_GRANDCHILDREN_GP_ZC',
 'ACS_TOT_HU_ZC',
 'ACS_TOT_HH_ZC',
 'ACS_AVG_HH_SIZE_ZC',
 'ACS_PCT_FEMALE_ZC',
 'ACS_PCT_MALE_ZC',
 'ACS_PCT_CTZ_US_BORN_ZC',
 'ACS_PCT_FOREIGN_BORN_ZC',
 'ACS_PCT_NON_CITIZEN_ZC',
 'ACS_PCT_API_LANG_ZC',
 'ACS_PCT_ENGL_NOT_ALL_ZC',
 'ACS_PCT_ENGL_NOT_WELL_ZC',
 'ACS_PCT_ENGLISH_ZC',
 'ACS_PCT_HH_LIMIT_ENGLISH_ZC',
 'ACS_PCT_OTH_EURP_ZC',
 'ACS_PCT_OTH_LANG_ZC',
 'ACS_PCT_SPANISH_ZC',
 'ACS_MEDIAN_AGE_ZC',
 'ACS_MEDIAN_AGE_FEMALE_ZC',
 'ACS_PCT_AGE_0_4_ZC',
 'ACS_PCT_AGE_5_9_ZC',
 'ACS_PCT_AGE_10_14_ZC',
 'ACS_PCT_AGE_15_17_ZC',
 'ACS_PCT_AGE_0_17_ZC',
 'ACS_PCT_AGE_18_29_ZC',
 'ACS_PCT_AGE_18_44_ZC',
 'ACS_PCT_AGE_30_44_ZC',
 'ACS_PCT_AGE_45_64_ZC',
 'ACS_PCT_HH_NO_COMP_DEV_ZC',
 'ACS_PCT_HH_SMARTPHONE_ZC',
 'ACS_PCT_HH_SMARTPHONE_ONLY_ZC',
 'ACS_PCT_HH_TABLET_ZC',
 'ACS_PCT_HH_TABLET_ONLY_ZC',
 'ACS_PCT_HH_PC_ZC',
 'ACS_PCT_HH_PC_ONLY_ZC',
 'ACS_PCT_HH_OTHER_COMP_ZC',
 'ACS_PCT_HH_OTHER_COMP_ONLY_ZC',
 'ACS_PCT_HH_INTERNET_ZC',
 'ACS_PCT_HH_INTERNET_NO_SUBS_ZC',
 'ACS_PCT_HH_CELLULAR_ZC',
 'ACS_PCT_HH_CELLULAR_ONLY_ZC',
 'ACS_PCT_HH_NO_INTERNET_ZC',
 'ACS_PCT_HH_SAT_INTERNET_ZC',
 'ACS_PCT_HH_DIAL_INTERNET_ONLY_ZC',
 'ACS_PCT_CHILD_1FAM_ZC',
 'ACS_PCT_HH_KID_1PRNT_ZC',
 'ACS_PCT_DIVORCED_F_ZC',
 'ACS_PCT_MARRIED_SP_AB_F_ZC',
 'ACS_PCT_MARRIED_SP_PR_F_ZC',
 'ACS_PCT_NVR_MARRIED_F_ZC',
 'ACS_PCT_POP_SAME_SEX_UNMRD_P_ZC',
 'ACS_PCT_POP_SAME_SEX_SPOUSE_ZC',
 'ACS_GINI_INDEX_ZC',
 'ACS_MDN_GRNDPRNT_NO_PRNT_INC_ZC',
 'ACS_MDN_GRNDPRNT_INC_ZC',
 'ACS_MEDIAN_HH_INC_AIAN_ZC',
 'ACS_MEDIAN_HH_INC_ASIAN_ZC',
 'ACS_MEDIAN_HH_INC_BLACK_ZC',
 'ACS_MEDIAN_HH_INC_HISP_ZC',
 'ACS_MEDIAN_HH_INC_MULTI_ZC',
 'ACS_MEDIAN_HH_INC_NHPI_ZC',
 'ACS_MEDIAN_HH_INC_OTHER_ZC',
 'ACS_MEDIAN_HH_INC_WHITE_ZC',
 'ACS_MEDIAN_HH_INC_ZC',
 'ACS_MEDIAN_INC_F_ZC',
 'ACS_MEDIAN_INC_M_ZC',
 'ACS_PCT_INC50_ABOVE65_ZC',
 'ACS_PCT_INC50_BELOW17_ZC',
 'ACS_PCT_HEALTH_INC_BELOW137_ZC',
 'ACS_PCT_HEALTH_INC_138_199_ZC',
 'ACS_PCT_HEALTH_INC_200_399_ZC',
 'ACS_PCT_HEALTH_INC_ABOVE400_ZC',
 'ACS_PCT_HH_INC_10000_ZC',
 'ACS_PCT_HH_INC_100000_ZC',
 'ACS_PCT_HH_INC_14999_ZC',
 'ACS_PCT_HH_INC_24999_ZC',
 'ACS_PCT_HH_INC_49999_ZC',
 'ACS_PCT_HH_INC_99999_ZC',
 'ACS_PCT_INC50_ZC',
 'ACS_PCT_NONVET_POV_18_64_ZC',
 'ACS_PCT_VET_POV_18_64_ZC',
 'ACS_PCT_PERSON_INC_100_124_ZC',
 'ACS_PCT_PERSON_INC_125_199_ZC',
 'ACS_PCT_PERSON_INC_ABOVE200_ZC',
 'ACS_PCT_PERSON_INC_BELOW99_ZC',
 'ACS_PER_CAPITA_INC_ZC',
 'ACS_PCT_POV_AIAN_ZC',
 'ACS_PCT_POV_ASIAN_ZC',
 'ACS_PCT_POV_BLACK_ZC',
 'ACS_PCT_POV_HISPANIC_ZC',
 'ACS_PCT_POV_MULTI_ZC',
 'ACS_PCT_POV_NHPI_ZC',
 'ACS_PCT_POV_OTHER_ZC',
 'ACS_PCT_POV_WHITE_ZC',
 'ACS_PCT_HH_1FAM_FOOD_STMP_ZC',
 'ACS_PCT_HH_FOOD_STMP_ZC',
 'ACS_PCT_HH_FOOD_STMP_BLW_POV_ZC',
 'ACS_PCT_HH_NO_FD_STMP_BLW_POV_ZC',
 'ACS_PCT_HH_PUB_ASSIST_ZC',
 'ACS_PCT_COLLEGE_ASSOCIATE_DGR_ZC',
 'ACS_PCT_BACHELOR_DGR_ZC',
 'ACS_PCT_NO_WORK_NO_SCHL_16_19_ZC',
 'ACS_PCT_GRADUATE_DGR_ZC',
 'ACS_PCT_HS_GRADUATE_ZC',
 'ACS_PCT_LT_HS_ZC',
 'ACS_PCT_POSTHS_ED_ZC',
 'ACS_PCT_VET_BACHELOR_ZC',
 'ACS_PCT_VET_COLLEGE_ZC',
 'ACS_PCT_VET_HS_ZC',
 'ACS_MEDIAN_HOME_VALUE_ZC',
 'ACS_MEDIAN_RENT_ZC',
 'ACS_MDN_OWNER_COST_MORTGAGE_ZC',
 'ACS_MDN_OWNER_COST_NO_MORTG_ZC',
 'ACS_MEDIAN_YEAR_BUILT_ZC',
 'ACS_PCT_10UNITS_ZC',
 'ACS_PCT_1UP_OWNER_1ROOM_ZC',
 'ACS_PCT_1UP_PERS_1ROOM_ZC',
 'ACS_PCT_1UP_RENT_1ROOM_ZC',
 'ACS_PCT_RENTER_HU_COST_30PCT_ZC',
 'ACS_PCT_RENTER_HU_COST_50PCT_ZC',
 'ACS_PCT_RENTER_HU_ZC',
 'ACS_PCT_RENTER_HU_CHILD_ZC',
 'ACS_PCT_VACANT_HU_ZC',
 'ACS_PCT_HU_NO_VEH_ZC',
 'ACS_PCT_PUB_COMMT_15MIN_ZC',
 'ACS_PCT_PUB_COMMT_29MIN_ZC',
 'ACS_PCT_PUB_COMMT_59MIN_ZC',
 'ACS_PCT_PUB_COMMT_60MINUP_ZC',
 'ACS_PCT_PUBL_TRANSIT_ZC',
 'ACS_PCT_TAXICAB_2WORK_ZC',
 'ACS_PCT_WALK_2WORK_ZC',
 'ACS_PCT_WORK_NO_CAR_ZC',
 'ACS_PCT_MEDICAID_ANY_ZC',
 'ACS_PCT_MEDICAID_ANY_BELOW64_ZC',
 'ACS_PCT_MEDICARE_ONLY_ZC',
 'ACS_PCT_OTHER_INS_ZC',
 'ACS_PCT_PVT_EMPL_DRCT_ZC',
 'ACS_PCT_PVT_EMPL_DRCT_BELOW64_ZC',
 'ACS_PCT_PRIVATE_ANY_ZC',
 'ACS_PCT_PRIVATE_ANY_BELOW64_ZC',
 'ACS_PCT_PRIVATE_EMPL_ZC',
 'ACS_PCT_PRIVATE_EMPL_BELOW64_ZC',
 'ACS_PCT_PRIVATE_MDCR_ZC',
 'ACS_PCT_PRIVATE_MDCR_35_64_ZC',
 'ACS_PCT_PRIVATE_OTHER_ZC',
 'ACS_PCT_PRIVATE_OTHER_BELOW64_ZC',
 'ACS_PCT_PRIVATE_SELF_ZC',
 'ACS_PCT_PRIVATE_SELF_BELOW64_ZC',
 'ACS_PCT_PUBLIC_ONLY_ZC',
 'ACS_PCT_PUBLIC_OTHER_ZC',
 'ACS_PCT_PUBLIC_OTHER_BELOW64_ZC',
 'ACS_PCT_SELF_MDCR_ABOVE35_ZC',
 'ACS_PCT_TRICARE_VA_ZC',
 'ACS_PCT_TRICARE_VA_BELOW64_ZC',
 'ACS_PCT_UNINSURED_ZC',
 'ACS_PCT_UNINSURED_BELOW64_ZC',
 'CEN_AREALAND_SQM_ZC',
 'CEN_POPDENSITY_ZC',
 'HIFLD_DIST_UC_ZP',
 'POS_DIST_ED_ZP',
 'POS_DIST_MEDSURG_ICU_ZP',
 'POS_DIST_TRAUMA_ZP',
 'POS_DIST_PED_ICU_ZP',
 'POS_DIST_OBSTETRICS_ZP',
 'POS_DIST_CLINIC_ZP',
 'POS_DIST_ALC_ZP',
 'CEN_AIAN_NH_IND']

In [75]:
len(cols_to_use)

185

In [76]:
# cal_sdoh = deepcopy()
cal_sdoh = cal_sdoh[cols_to_use]

In [77]:
cal_sdoh.to_csv("cal_sdoh_useful.csv", index=False)

In [78]:
print(cal_sdoh.head())
cal_sdoh = cal_sdoh.drop(['YEAR','STATEFIPS','STATE','REGION'],axis=1)

   YEAR  STATEFIPS  ZIPCODE  ZCTA       STATE REGION  ACS_TOT_POP_WT_ZC  \
0  2020          6    93928   NaN  California    NaN                NaN
1  2020          6    95836   NaN  California    NaN                NaN
2  2020          6    91023   NaN  California    NaN                NaN
3  2020          6    93581   NaN  California    NaN                NaN
4  2020          6    93530   NaN  California    NaN                NaN

   ACS_TOT_POP_US_ABOVE1_ZC  ACS_TOT_POP_ABOVE5_ZC  ACS_TOT_POP_ABOVE15_ZC  \
0                       NaN                    NaN                     NaN
1                       NaN                    NaN                     NaN
2                       NaN                    NaN                     NaN
3                       NaN                    NaN                     NaN
4                       NaN                    NaN                     NaN

   ...  CEN_POPDENSITY_ZC  HIFLD_DIST_UC_ZP  POS_DIST_ED_ZP  \
0  ...                NaN             26.02           19.44
1  ...                NaN              6.58           10.30
2  ...                NaN              5.72            4.29
3  ...                NaN             33.30            0.24
4  ...                NaN             78.62           20.67

   POS_DIST_MEDSURG_ICU_ZP  POS_DIST_TRAUMA_ZP  POS_DIST_PED_ICU_ZP  \
0                    19.44               56.02                96.97
1                    10.30               12.87                12.32
2                     4.29                7.92                 7.92
3                    33.29               33.29                35.91
4                    41.74               84.90                83.12

   POS_DIST_OBSTETRICS_ZP  POS_DIST_CLINIC_ZP  POS_DIST_ALC_ZP  \
0                   19.44               19.17            53.74
1                   12.32                9.29            10.30
2                    6.47                6.86             4.29
3                   33.29                0.83            35.69
4                   20.67               20.69            76.99

   CEN_AIAN_NH_IND
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN

[5 rows x 185 columns]

In [68]:
# cal_sdoh = cal_sdoh.reset_index(drop=True)

In [79]:
cal_sdoh

,ZIPCODE,ZCTA,ACS_TOT_POP_WT_ZC,ACS_TOT_POP_US_ABOVE1_ZC,ACS_TOT_POP_ABOVE5_ZC,ACS_TOT_POP_ABOVE15_ZC,ACS_TOT_POP_ABOVE16_ZC,ACS_TOT_POP_16_19_ZC,ACS_TOT_POP_ABOVE25_ZC,ACS_TOT_OWN_CHILD_BELOW17_ZC,...,CEN_POPDENSITY_ZC,HIFLD_DIST_UC_ZP,POS_DIST_ED_ZP,POS_DIST_MEDSURG_ICU_ZP,POS_DIST_TRAUMA_ZP,POS_DIST_PED_ICU_ZP,POS_DIST_OBSTETRICS_ZP,POS_DIST_CLINIC_ZP,POS_DIST_ALC_ZP,CEN_AIAN_NH_IND
0,93928,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,26.02,19.44,19.44,56.02,96.97,19.44,19.17,53.74,NaN
1,95836,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,6.58,10.30,10.30,12.87,12.32,12.32,9.29,10.30,NaN
2,91023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,5.72,4.29,4.29,7.92,7.92,6.47,6.86,4.29,NaN
3,93581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,33.30,0.24,33.29,33.29,35.91,33.29,0.83,35.69,NaN
4,93530,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,78.62,20.67,41.74,84.90,83.12,20.67,20.69,76.99,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2580,96152,96150.0,30369.0,30169.0,29007.0,26471.0,26248.0,1398.0,22739.0,4106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2581,96151,96150.0,30369.0,30169.0,29007.0,26471.0,26248.0,1398.0,22739.0,4106.0,...,NaN,2.76,2.88,2.88,2.88,2.88,2.88,2.81,20.82,0.0
2582,96150,96150.0,30369.0,30169.0,29007.0,26471.0,26248.0,1398.0,22739.0,4106.0,...,NaN,0.65,0.56,0.56,0.56,0.56,0.56,0.50,22.68,0.0
2583,96161,96161.0,18782.0,18658.0,17737.0,15234.0,15121.0,675.0,13581.0,4046.0,...,NaN,1.12,1.05,1.05,24.59,24.59,1.05,0.99,23.58,0.0
2584,96160,96161.0,18782.0,18658.0,17737.0,15234.0,15121.0,675.0,13581.0,4046.0,...,NaN,1.06,0.94,0.94,24.73,24.73,0.94,0.91,23.25,0.0

In [55]:
#num values having no zipcodes
maindata[maindata['ZIPCODE'].isna()]['Readmitted (Y/N)'].value_counts()

N    78
Name: Readmitted (Y/N), dtype: int64

In [151]:
adi_data = pd.read_csv('CA_2020_ADI_9 Digit Zip Code_v3.2.csv')

# Now you can list all sheets in the file
adi_data.columns

/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py:3062: DtypeWarning: Columns (3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

Index(['ZIP_4', 'GISJOIN', 'FIPS', 'ADI_NATRANK', 'ADI_STATERANK', 'TYPE'], dtype='object')

In [152]:
adi_data.head()

       ZIP_4          GISJOIN          FIPS ADI_NATRANK ADI_STATERANK TYPE
0  900010192  G06003702393301  6.037239e+10          27             8
1  900010191  G06003702393301  6.037239e+10          27             8
2  900010200  G06003702393301  6.037239e+10          27             8
3  900010201  G06003702393301  6.037239e+10          27             8
4  900010202  G06003702393301  6.037239e+10          27             8

In [153]:
adi_data

,ZIP_4,GISJOIN,FIPS,ADI_NATRANK,ADI_STATERANK,TYPE
0,900010192,G06003702393301,6.037239e+10,27,8,
1,900010191,G06003702393301,6.037239e+10,27,8,
2,900010200,G06003702393301,6.037239e+10,27,8,
3,900010201,G06003702393301,6.037239e+10,27,8,
4,900010202,G06003702393301,6.037239e+10,27,8,
...,...,...,...,...,...,...
6039917,976353049,G41003709602006,4.103796e+11,50,8,
6039918,976359700,G41003709602006,4.103796e+11,50,8,
6039919,976359701,G41003709602006,4.103796e+11,50,8,
6039920,976359703,G41003709602006,4.103796e+11,50,8,
6039921,976359704,G41003709602006,4.103796e+11,50,8,

In [82]:
maindata['ZIPCODE'] = maindata['ZIPCODE'].astype('Int64')
cal_sdoh['ZIPCODE'] = cal_sdoh['ZIPCODE'].astype('Int64')

In [83]:
maindata_with_sdoh= maindata.merge(cal_sdoh, on='ZIPCODE', how='left')

In [84]:
maindata_with_sdoh

,Fiscal Year,ECG,Mutated MRN,Diabetes (Y/N),Meth/Cocaine use(Y/N),Readmitted (Y/N),HDP Diagnosis (readmission episode) or NA,Delivery Date,Readmission date,Age,...,CEN_POPDENSITY_ZC,HIFLD_DIST_UC_ZP,POS_DIST_ED_ZP,POS_DIST_MEDSURG_ICU_ZP,POS_DIST_TRAUMA_ZP,POS_DIST_PED_ICU_ZP,POS_DIST_OBSTETRICS_ZP,POS_DIST_CLINIC_ZP,POS_DIST_ALC_ZP,CEN_AIAN_NH_IND
0,2021,"Y, 4 month prior to del",7887439,1,0,Y,preeclampsia with SF,2021-07-04,2021-07-08 00:00:00,38.0,...,NaN,1.75,1.11,1.11,1.11,5.22,1.11,1.07,1.56,0.0
1,2021,"Y, in labor",2392172,0,0,Y,preeclampsia with SF,2021-07-06,2021-07-12 00:00:00,34.0,...,NaN,23.11,11.20,11.20,33.58,33.58,11.20,6.82,37.17,0.0
2,2021,"Y, postpartum",1252118,0,0,Y,preeclampsia with SF,2021-07-22,2021-07-29 00:00:00,31.0,...,NaN,1.55,2.19,2.19,2.19,2.30,2.19,7.62,1.88,0.0
3,2021,N,7872701,1,0,Y,superimposed with SF,2021-08-03,2021-08-12 00:00:00,33.0,...,NaN,1.34,3.46,3.46,3.43,3.43,3.46,1.73,5.07,0.0
4,2021,N,7954972,1,0,Y,preeclampsia with SF,2021-08-06,2021-08-14 00:00:00,44.0,...,NaN,2.17,2.44,2.44,4.89,3.61,3.61,2.36,2.44,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340,2023,N,8093931,1,0,N,NaN,2023-05-28,NaN,29.0,...,NaN,1.76,2.43,2.43,2.43,6.17,2.43,1.81,4.70,0.0
341,2023,N,8105947,1,0,N,NaN,2023-05-30,NaN,38.0,...,NaN,6.20,5.64,7.25,7.47,8.41,7.25,10.35,5.64,0.0
342,2023,N,7662725,0,0,N,NaN,2023-05-30,NaN,29.0,...,NaN,0.95,0.93,0.93,9.25,15.66,0.93,0.91,9.25,0.0
343,2023,N,8351519,0,0,N,NaN,2023-05-31,NaN,37.0,...,NaN,3.53,3.78,4.32,4.79,5.90,4.32,7.40,3.78,0.0
344,2023,"Y, 2023",8299905,0,0,N,NaN,2023-05-31,NaN,44.0,...,NaN,3.38,4.05,4.05,4.71,4.05,4.05,1.13,5.59,0.0

In [85]:
maindata_with_sdoh.to_csv("zipcode_with_sdoh_only.csv")

In [154]:
maindata_with_sdoh['ZIP_4'] = maindata_with_sdoh['ZIP_4'].astype('Int64')
adi_data['ZIP_4'] = adi_data['ZIP_4'].astype('Int64')

In [87]:
maindata_with_sdoh_adi= maindata_with_sdoh.merge(adi_data, on='ZIP_4', how='left')

In [88]:
maindata_with_sdoh_adi

,Fiscal Year,ECG,Mutated MRN,Diabetes (Y/N),Meth/Cocaine use(Y/N),Readmitted (Y/N),HDP Diagnosis (readmission episode) or NA,Delivery Date,Readmission date,Age,...,POS_DIST_PED_ICU_ZP,POS_DIST_OBSTETRICS_ZP,POS_DIST_CLINIC_ZP,POS_DIST_ALC_ZP,CEN_AIAN_NH_IND,GISJOIN,FIPS,ADI_NATRANK,ADI_STATERANK,TYPE
0,2021,"Y, 4 month prior to del",7887439,1,0,Y,preeclampsia with SF,2021-07-04,2021-07-08 00:00:00,38.0,...,5.22,1.11,1.07,1.56,0.0,G06006700047012,6.067005e+10,54,10,
1,2021,"Y, in labor",2392172,0,0,Y,preeclampsia with SF,2021-07-06,2021-07-12 00:00:00,34.0,...,33.58,11.20,6.82,37.17,0.0,G06001700314051,6.017031e+10,30,8,
2,2021,"Y, postpartum",1252118,0,0,Y,preeclampsia with SF,2021-07-22,2021-07-29 00:00:00,31.0,...,2.30,2.19,7.62,1.88,0.0,NaN,NaN,NaN,NaN,NaN
3,2021,N,7872701,1,0,Y,superimposed with SF,2021-08-03,2021-08-12 00:00:00,33.0,...,3.43,3.46,1.73,5.07,0.0,NaN,NaN,NaN,NaN,NaN
4,2021,N,7954972,1,0,Y,preeclampsia with SF,2021-08-06,2021-08-14 00:00:00,44.0,...,3.61,3.61,2.36,2.44,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340,2023,N,8093931,1,0,N,NaN,2023-05-28,NaN,29.0,...,6.17,2.43,1.81,4.70,0.0,G06006700074161,6.067007e+10,44,9,
341,2023,N,8105947,1,0,N,NaN,2023-05-30,NaN,38.0,...,8.41,7.25,10.35,5.64,0.0,NaN,NaN,NaN,NaN,NaN
342,2023,N,7662725,0,0,N,NaN,2023-05-30,NaN,29.0,...,15.66,0.93,0.91,9.25,0.0,G06011300105104,6.113011e+10,6,3,
343,2023,N,8351519,0,0,N,NaN,2023-05-31,NaN,37.0,...,5.90,4.32,7.40,3.78,0.0,G06006700089121,6.067009e+10,29,8,
344,2023,"Y, 2023",8299905,0,0,N,NaN,2023-05-31,NaN,44.0,...,4.05,4.05,1.13,5.59,0.0,G06011300102031,6.113010e+10,51,10,

In [155]:
adi_data['ZIP_4'] = adi_data['ZIP_4'].astype('str')
adi_data['ZIP_4'].str[:5]

0          90001
1          90001
2          90001
3          90001
4          90001
           ...
6039917    97635
6039918    97635
6039919    97635
6039920    97635
6039921    97635
Name: ZIP_4, Length: 6039922, dtype: object

In [94]:
adi_data['ZIP_4'].str[:5].value_counts()

95532    9998
94974    9998
91495    9997
91188    9997
91482    9997
         ...
94205       1
94284       1
92698       1
91756       1
95191       1
Name: ZIP_4, Length: 2548, dtype: int64

In [157]:

adi_data[adi_data['ADI_STATERANK']=='PH'] #or adi_data['ADI_STATERANK']=='PH' or adi_data['ADI_STATERANK']=='PH-GQ']

adi_data=adi_data.drop(adi_data[adi_data['ADI_STATERANK']=='PH'].index)
adi_data=adi_data.drop(adi_data[adi_data['ADI_STATERANK']=='GQ'].index)
adi_data=adi_data.drop(adi_data[adi_data['ADI_STATERANK']=='GQ-PH'].index)
adi_data=adi_data.drop(adi_data[adi_data['ADI_STATERANK']=='QDI'].index)
adi_data=adi_data.drop(adi_data[adi_data['ADI_STATERANK']=='PH-GQ'].index)

temp=adi_data.groupby(adi_data['ZIP_4'].str[:5])

In [158]:
for idx,zip5 in enumerate(temp.groups.keys()):
    grp = temp.get_group(zip5)
    # print(grp['ADI_STATERANK'])
    grp['ADI_STATERANK'] = grp['ADI_STATERANK'].astype('Float64')
    print(idx)
    adi_data.loc[adi_data[adi_data['ZIP_4'].str[:5]==zip5].index,'Avg_State_Rank'] =grp['ADI_STATERANK'].mean()
    # print(grp.astype('Int64').mean())
    # break

<ipython-input-158-0e48dd9c97b0>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grp['ADI_STATERANK'] = grp['ADI_STATERANK'].astype('Float64')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1595
1596
1597
1598
1599
1600
1601
1602
1603
1604
1605
1606
1607
1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626
1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
1668
1669
1670
1671
1672
1673
1674
1675
1676
1677
1678
1679
1680
1681
1682
1683
1684
1685
1686
1687
1688
1689
1690
1691
1692
1693
1694
1695
1696
1697
1698
1699
1700
1701
1702
1703
1704
1705
1706
1707
1708
1709
1710
1711
1712
1713
1714
1715
1716
1717
1718
1719
1720
1721
1722
1723
1724
1725
1726
1727
1728
1729
1730
1731
1732
1733
1734
1735
1736
1737
1738
1739
1740
1741
1742
1743
1744
1745
1746
1747
1748
1749
1750
1751
1752
1753
1754
1755
1756
1757
1758
1759
1760
1761
1762
1763
1764
1765
1766
1767
1768
1769
1770
1771
1772
1773
1774
1775
1776
1777
1778
1779
1780
1781
1782
1783
1784
1785
1786
1787
1788
1789
1790
1791
1792
1793
1794
1795
1796
1797
1798
1799
1800
1801
1802
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
1813
1814
1815
1816
1817
1818
1819
1820
1821
1822
1823
1824
1825
1826
1827
1828
1829
1830
1831
1832
1833
1834
1835
1836
1837
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
1849
1850
1851
1852
1853
1854
1855
1856
1857
1858
1859
1860
1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066
2067
2068
2069
2070
2071
2072
2073
2074
2075
2076
2077
2078
2079
2080
2081
2082
2083
2084
2085
2086
2087
2088
2089
2090
2091
2092
2093
2094
2095
2096
2097
2098
2099
2100
2101
2102
2103
2104
2105
2106
2107
2108
2109
2110
2111
2112
2113
2114
2115
2116
2117
2118
2119
2120
2121
2122
2123
2124
2125
2126
2127
2128
2129
2130
2131
2132
2133
2134
2135
2136
2137
2138
2139
2140
2141
2142
2143
2144
2145
2146
2147
2148
2149
2150
2151
2152
2153
2154
2155
2156
2157
2158
2159
2160
2161
2162
2163
2164
2165
2166
2167
2168
2169
2170
2171
2172
2173
2174
2175
2176
2177
2178
2179
2180
2181
2182
2183
2184
2185
2186
2187
2188
2189
2190
2191
2192
2193
2194
2195
2196
2197
2198
2199
2200
2201
2202
2203
2204
2205
2206
2207
2208
2209
2210
2211
2212
2213
2214
2215
2216
2217
2218
2219
2220
2221
2222
2223
2224
2225
2226
2227
2228
2229
2230
2231
2232
2233
2234
2235
2236
2237
2238
2239
2240
2241
2242
2243
2244
2245
2246
2247
2248
2249
2250
2251
2252
2253
2254
2255
2256
2257
2258
2259
2260
2261
2262
2263
2264
2265
2266
2267
2268
2269
2270
2271
2272
2273
2274
2275
2276
2277
2278
2279
2280
2281
2282
2283
2284
2285
2286
2287
2288
2289
2290
2291
2292
2293
2294
2295
2296
2297
2298
2299
2300
2301
2302
2303
2304
2305
2306
2307
2308
2309
2310
2311
2312
2313
2314
2315
2316
2317
2318
2319
2320
2321
2322
2323
2324
2325
2326
2327
2328
2329
2330
2331
2332
2333
2334
2335
2336
2337
2338
2339
2340
2341
2342
2343
2344
2345
2346
2347
2348
2349
2350
2351
2352
2353
2354
2355
2356
2357
2358
2359
2360
2361
2362
2363
2364
2365
2366
2367
2368
2369
2370
2371
2372
2373
2374
2375
2376
2377
2378
2379
2380
2381
2382
2383
2384
2385
2386
2387
2388
2389
2390
2391
2392
2393
2394
2395
2396
2397
2398
2399
2400
2401
2402
2403
2404
2405
2406
2407
2408
2409
2410
2411
2412
2413
2414
2415
2416
2417
2418
2419
2420
2421
2422
2423
2424
2425
2426
2427
2428
2429
2430
2431
2432
2433
2434
2435
2436
2437
2438
2439
2440
2441
2442
2443
2444
2445
2446
2447
2448
2449
2450
2451
2452
2453
2454
2455
2456
2457
2458
2459
2460
2461
2462
2463
2464
2465
2466
2467
2468
2469
2470
2471
2472
2473
2474
2475
2476
2477
2478
2479
2480
2481
2482
2483
2484
2485
2486
2487
2488
2489
2490

In [156]:
adi_data['ADI_STATERANK'].value_counts()

10       796397
9        676308
8        591231
5        579697
2        566877
1        559622
6        549413
3        529338
4        519555
7        483117
GQ       142901
PH        20657
GQ-PH     11382
8          2841
4          2776
6          2650
QDI        2418
5           865
3           706
1           310
7           233
2           229
Name: ADI_STATERANK, dtype: int64

In [161]:
adi_data[adi_data['Avg_State_Rank'].isna()]

Empty DataFrame
Columns: [ZIP_4, GISJOIN, FIPS, ADI_NATRANK, ADI_STATERANK, TYPE, Avg_State_Rank]
Index: []

In [162]:
adi_data.to_csv("adi_with_avgstateranks.csv",index=False)

In [129]:
maindata_with_sdoh_adi[maindata_with_sdoh_adi['ADI_STATERANK'].isna()]

,Fiscal Year,ECG,Mutated MRN,Diabetes (Y/N),Meth/Cocaine use(Y/N),Readmitted (Y/N),HDP Diagnosis (readmission episode) or NA,Delivery Date,Readmission date,Age,...,POS_DIST_PED_ICU_ZP,POS_DIST_OBSTETRICS_ZP,POS_DIST_CLINIC_ZP,POS_DIST_ALC_ZP,CEN_AIAN_NH_IND,GISJOIN,FIPS,ADI_NATRANK,ADI_STATERANK,TYPE
2,2021,"Y, postpartum",1252118,0,0,Y,preeclampsia with SF,2021-07-22,2021-07-29 00:00:00,31.0,...,2.30,2.19,7.62,1.88,0.0,NaN,NaN,NaN,NaN,NaN
3,2021,N,7872701,1,0,Y,superimposed with SF,2021-08-03,2021-08-12 00:00:00,33.0,...,3.43,3.46,1.73,5.07,0.0,NaN,NaN,NaN,NaN,NaN
4,2021,N,7954972,1,0,Y,preeclampsia with SF,2021-08-06,2021-08-14 00:00:00,44.0,...,3.61,3.61,2.36,2.44,0.0,NaN,NaN,NaN,NaN,NaN
5,2021,"Y, 15 weeks",7883393,0,0,Y,preeclampsia with SF,2021-09-20,2021-09-28 00:00:00,33.0,...,17.67,9.33,8.80,20.00,0.0,NaN,NaN,NaN,NaN,NaN
7,2021,"Y, 1 week postpartum",7798420,1,0,Y,preeclampsia with SF,2021-09-29,2021-10-04 00:00:00,30.0,...,7.40,7.40,4.83,5.38,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,2023,N,7889858,1,0,N,NaN,2023-05-14,NaN,20.0,...,5.22,1.11,1.07,1.56,0.0,NaN,NaN,NaN,NaN,NaN
322,2023,N,8113756,0,0,N,NaN,2023-05-15,NaN,32.0,...,7.40,7.40,4.83,5.38,0.0,NaN,NaN,NaN,NaN,NaN
328,2023,N,8112290,0,0,N,NaN,2023-05-21,NaN,38.0,...,11.51,5.30,5.02,5.46,0.0,NaN,NaN,NaN,NaN,NaN
331,2023,N,7828133,0,0,N,NaN,2023-05-22,NaN,33.0,...,0.13,0.13,0.59,2.56,0.0,NaN,NaN,NaN,NaN,NaN
341,2023,N,8105947,1,0,N,NaN,2023-05-30,NaN,38.0,...,8.41,7.25,10.35,5.64,0.0,NaN,NaN,NaN,NaN,NaN